# Generated by Django 5.0.9 on 2024-09-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_question_options_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
    ]
