# Generated by Django 5.0.9 on 2024-09-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereport',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.quiz'),
        ),
    ]
