# Generated by Django 5.0.9 on 2024-09-29 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_performancereport_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='organization.quiz'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
