# Generated by Django 5.0.9 on 2024-10-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_question_quiz_delete_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('country', models.CharField(max_length=55)),
                ('mobile', models.CharField(max_length=55)),
            ],
        ),
    ]
